services:
  mongodb:
      image: mongo:4.4.6
      container_name: mongo
      restart: always
      environment:
       - MONGO_INITDB_ROOT_USERNAME=usuario
       - MONGO_INITDB_ROOT_PASSWORD=senha
      volumes:
        - ./mongo_data:/data/db
  kasm:
    container_name: kasm
    build: .
    privileged: true
    ports:
      - "80:8080"  # Interface gráfica
      - "6080:80"  # Interface gráfica
      - "8000:8000"  # API de automação
      - "5000:5000"  # captura continua
    restart: always
    environment:
      - RESOLUTION=1080x768
      - DISPLAY=:1
      - HOME=/root
      - USER=root
      - OPENBOX_ARGS=--startup "python /home/ubuntu/app.py"
    depends_on:
        - mongodb
volumes:
  mongo_data:
